version: "3.7"
name: "seliger-kamen"

services:
  seliger-kamen-caddy:
    container_name: seliger-kamen-caddy
    image: caddy:2.11.2
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
    networks:
      - seliger-kamen

  seliger-kamen-frontend:
    image: danilkavolkov/seliger-kamen-frontend:latest
    container_name: seliger-kamen-frontend
    networks:
      - seliger-kamen

  seliger-kamen-directus:
    image: danilkavolkov/seliger-kamen-directus:latest
    container_name: seliger-kamen-directus
    networks:
      - seliger-kamen
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    user: "1000:1000"
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET: ${ADMIN_SECRET}
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "array:'self',blob:,https://*"
      EXTENSIONS_AUTO_RELOAD: true
networks:
  seliger-kamen:
    driver: bridge
