services:
  seliger-kamen-caddy:
    image: caddy:2.11.2
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - seliger-kamen

  seliger-kamen-frontend:
    image: danilkavolkov/seliger-kamen-frontend:${DOCKER_HASH}
    networks:
      - seliger-kamen
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2

  seliger-kamen-directus:
    image: danilkavolkov/seliger-kamen-directus:${DOCKER_HASH}
    networks:
      - seliger-kamen
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    user: "1000:1000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8055" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 2
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET: ${ADMIN_SECRET}
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "array:'self',blob:,https://*"
      EXTENSIONS_AUTO_RELOAD: "true"
      CACHE_ENABLED: "true"
      LOG_LEVEL: "debug"
      CACHE_AUTO_PURGE: "true"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "smtp.timeweb.ru"
      EMAIL_SMTP_PORT: "465"
      EMAIL_FROM: ${SMTP_USER}
      EMAIL_SMTP_USER: ${SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_SMTP_SECURE: "true"

networks:
  seliger-kamen:
    driver: overlay
    attachable: true

volumes:
  caddy_data: